name: Publish release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'     
        required: true

jobs:
  publish:
    name: Publish to Marketplace
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: vsce publish
        run: npm exec -- vsce publish ${{ github.event.inputs.version }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
