name: Publish release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish & tag & push (without "v" prefix)'
        required: true
      changelog_updated:
        description: 'Did you update the changelog? ("yes")'
        required: true

jobs:
  publish:
    name: Publish to VS Code Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Ensure changelog is updated
        if: ${{ github.event.inputs.changelog_updated != 'yes' }}
        run: |
          echo "Response: ${{ github.event.inputs.changelog_updated }} (expected yes)"
          exit 1
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Read Node.js version
        id: nodejs-version
        run: |
          content=`cat ./.nvmrc`
          echo "::set-output name=content::$content"
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          # See https://github.com/actions/setup-node/issues/32
          node-version: ${{ steps.nodejs-version.outputs.content }}
      - name: Install dependencies
        run: npm ci
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: "~1.0"
      - name: npm test
        run: xvfb-run --auto-servernum --listen-tcp --server-args='-screen 0 1024x768x24' npm test
      - name: Configure git author
        run: |
          git config user.email "hashibot-feedback@hashicorp.com"
          git config user.name "HashiBot"
      - name: vsce publish
        run: npx -- vsce publish ${{ github.event.inputs.version }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: git push
        run: |
          $defaultBranch = git branch --show-current
          git push origin $defaultBranch
          git push origin v${{ github.event.inputs.version }}
